"""Ports (protocols) for the I/O boundary — dependency inversion.

state.py / bootstrap.py depend on these, NOT on the concrete pyobjc/osascript
modules, so unit tests inject fakes and never import pyobjc (ARCHITECTURE §7.1).
"""
from __future__ import annotations

from typing import Callable, Optional, Protocol, runtime_checkable


@runtime_checkable
class KeysPort(Protocol):
    def cmd_esc(self) -> None: ...
    def reveal_claude(self) -> None: ...  # Cmd+Shift+Esc → claude-vscode.editor.open (built-in)
    def esc(self) -> None: ...
    def type_text(self, s: str) -> None: ...
    def backspace(self, n: int) -> None: ...
    def ret(self) -> None: ...
    def clear(self) -> None: ...  # Cmd+A + Delete


@runtime_checkable
class AXPort(Protocol):
    def set_manual_a11y(self) -> None: ...
    def read_box(self) -> Optional[str]: ...
    def read_box_settled(self) -> Optional[str]: ...   # wait out the post-dictation refill race
    # textarea observer — command words arrive via AXValueChanged
    def observe_box(self, on_change: Callable[[str], None]) -> bool: ...
    def stop_observing_box(self) -> None: ...
    # dictation button = ground truth for the DICTATING state
    def dictation_on(self) -> Optional[bool]: ...          # True=on, False=off, None=not found
    def press_dictation(self) -> None: ...                 # unconditional AXPress (a request)
    def observe_dictation(self, on_change: Callable[[bool], None]) -> bool: ...
    def stop_observing_dictation(self) -> None: ...


@runtime_checkable
class SystemPort(Protocol):
    def frontmost_bundle_id(self) -> Optional[str]: ...
    def window_title(self) -> Optional[str]: ...
    def is_app_running(self) -> bool: ...
    def launch_app(self) -> None: ...
    def open_path(self, path: str) -> None: ...
    def raise_app(self) -> None: ...
