"""Ports (protocols) for the I/O boundary — dependency inversion.

state.py / bootstrap.py depend on these, NOT on the concrete pyobjc/osascript
modules, so unit tests inject fakes and never import pyobjc (ARCHITECTURE §7.1).
"""
from __future__ import annotations

from typing import Callable, Optional, Protocol, runtime_checkable


@runtime_checkable
class KeysPort(Protocol):
    def cmd_d(self) -> None: ...
    def cmd_esc(self) -> None: ...
    def esc(self) -> None: ...
    def type_text(self, s: str) -> None: ...
    def backspace(self, n: int) -> None: ...
    def ret(self) -> None: ...
    def clear(self) -> None: ...  # Cmd+A + Delete


@runtime_checkable
class AXPort(Protocol):
    def set_manual_a11y(self) -> None: ...
    def read_box(self) -> Optional[str]: ...
    def start_observing(self, on_change: Callable[[str], None]) -> bool: ...
    def stop_observing(self) -> None: ...


@runtime_checkable
class SystemPort(Protocol):
    def frontmost_bundle_id(self) -> Optional[str]: ...
    def window_title(self) -> Optional[str]: ...
    def is_app_running(self) -> bool: ...
    def launch_app(self) -> None: ...
    def open_path(self, path: str) -> None: ...
    def raise_app(self) -> None: ...
